//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.GetAuthorizations {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.aquasoft.eu/iska", ConfigurationName="GetAuthorizations.AuthorizationServiceSoap")]
    public interface AuthorizationServiceSoap {
        
        // CODEGEN: Generating message contract since message GetAuthorizationsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aquasoft.eu/iska/GetAuthorizations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Blog.GetAuthorizations.GetAuthorizationsResponse GetAuthorizations(Blog.GetAuthorizations.GetAuthorizationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aquasoft.eu/iska/GetAuthorizations", ReplyAction="*")]
        System.Threading.Tasks.Task<Blog.GetAuthorizations.GetAuthorizationsResponse> GetAuthorizationsAsync(Blog.GetAuthorizations.GetAuthorizationsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aquasoft.eu/iska")]
    public partial class Access : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("User");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aquasoft.eu/iska")]
    public partial class RepresentativePerson : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string frontDegreeField;
        
        private string backDegreeField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private System.Guid representativePersonIdField;
        
        private System.Guid representativePersonVersionIdField;
        
        private System.Guid authorizedPersonIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FrontDegree {
            get {
                return this.frontDegreeField;
            }
            set {
                this.frontDegreeField = value;
                this.RaisePropertyChanged("FrontDegree");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BackDegree {
            get {
                return this.backDegreeField;
            }
            set {
                this.backDegreeField = value;
                this.RaisePropertyChanged("BackDegree");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.Guid RepresentativePersonId {
            get {
                return this.representativePersonIdField;
            }
            set {
                this.representativePersonIdField = value;
                this.RaisePropertyChanged("RepresentativePersonId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.Guid RepresentativePersonVersionId {
            get {
                return this.representativePersonVersionIdField;
            }
            set {
                this.representativePersonVersionIdField = value;
                this.RaisePropertyChanged("RepresentativePersonVersionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.Guid AuthorizedPersonId {
            get {
                return this.authorizedPersonIdField;
            }
            set {
                this.authorizedPersonIdField = value;
                this.RaisePropertyChanged("AuthorizedPersonId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aquasoft.eu/iska")]
    public partial class AuthPersonContact : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid idField;
        
        private ContactKind contactTypeField;
        
        private string contactValueField;
        
        private string contactNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ContactKind ContactType {
            get {
                return this.contactTypeField;
            }
            set {
                this.contactTypeField = value;
                this.RaisePropertyChanged("ContactType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ContactValue {
            get {
                return this.contactValueField;
            }
            set {
                this.contactValueField = value;
                this.RaisePropertyChanged("ContactValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ContactName {
            get {
                return this.contactNameField;
            }
            set {
                this.contactNameField = value;
                this.RaisePropertyChanged("ContactName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aquasoft.eu/iska")]
    public enum ContactKind {
        
        /// <remarks/>
        Phone,
        
        /// <remarks/>
        Mobile,
        
        /// <remarks/>
        Email,
        
        /// <remarks/>
        Fax,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aquasoft.eu/iska")]
    public partial class AuthPersonQualification : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int qualificationIdField;
        
        private System.Guid authorizedPersonIdField;
        
        private System.DateTime validFromField;
        
        private System.DateTime validToField;
        
        private AuthPersonContact[] contactsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int QualificationId {
            get {
                return this.qualificationIdField;
            }
            set {
                this.qualificationIdField = value;
                this.RaisePropertyChanged("QualificationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid AuthorizedPersonId {
            get {
                return this.authorizedPersonIdField;
            }
            set {
                this.authorizedPersonIdField = value;
                this.RaisePropertyChanged("AuthorizedPersonId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime ValidFrom {
            get {
                return this.validFromField;
            }
            set {
                this.validFromField = value;
                this.RaisePropertyChanged("ValidFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime ValidTo {
            get {
                return this.validToField;
            }
            set {
                this.validToField = value;
                this.RaisePropertyChanged("ValidTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public AuthPersonContact[] Contacts {
            get {
                return this.contactsField;
            }
            set {
                this.contactsField = value;
                this.RaisePropertyChanged("Contacts");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aquasoft.eu/iska")]
    public partial class AuthPersonAddress : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid idField;
        
        private AuthPersonAddressType addressTypeField;
        
        private string streetField;
        
        private string cityField;
        
        private string zipField;
        
        private string numberField;
        
        private string orientationNumberField;
        
        private string countryField;
        
        private string districtField;
        
        private string regionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AuthPersonAddressType AddressType {
            get {
                return this.addressTypeField;
            }
            set {
                this.addressTypeField = value;
                this.RaisePropertyChanged("AddressType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("Street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
                this.RaisePropertyChanged("Zip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string OrientationNumber {
            get {
                return this.orientationNumberField;
            }
            set {
                this.orientationNumberField = value;
                this.RaisePropertyChanged("OrientationNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string District {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
                this.RaisePropertyChanged("District");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
                this.RaisePropertyChanged("Region");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aquasoft.eu/iska")]
    public enum AuthPersonAddressType {
        
        /// <remarks/>
        Residence,
        
        /// <remarks/>
        Contact,
        
        /// <remarks/>
        Delivery,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aquasoft.eu/iska")]
    public partial class AuthPerson : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string frontDegreeField;
        
        private string backDegreeField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string organizationNameField;
        
        private string legalFormField;
        
        private string iCOField;
        
        private AuthorizedPersonType authorizedPersonTypeField;
        
        private System.Guid authorizedPersonIdField;
        
        private System.Guid authorizedPersonVersionIdField;
        
        private IszrVerificationStatus iszrVerificationStatusField;
        
        private AuthPersonAddress[] addressesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FrontDegree {
            get {
                return this.frontDegreeField;
            }
            set {
                this.frontDegreeField = value;
                this.RaisePropertyChanged("FrontDegree");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BackDegree {
            get {
                return this.backDegreeField;
            }
            set {
                this.backDegreeField = value;
                this.RaisePropertyChanged("BackDegree");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string OrganizationName {
            get {
                return this.organizationNameField;
            }
            set {
                this.organizationNameField = value;
                this.RaisePropertyChanged("OrganizationName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string LegalForm {
            get {
                return this.legalFormField;
            }
            set {
                this.legalFormField = value;
                this.RaisePropertyChanged("LegalForm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ICO {
            get {
                return this.iCOField;
            }
            set {
                this.iCOField = value;
                this.RaisePropertyChanged("ICO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public AuthorizedPersonType AuthorizedPersonType {
            get {
                return this.authorizedPersonTypeField;
            }
            set {
                this.authorizedPersonTypeField = value;
                this.RaisePropertyChanged("AuthorizedPersonType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.Guid AuthorizedPersonId {
            get {
                return this.authorizedPersonIdField;
            }
            set {
                this.authorizedPersonIdField = value;
                this.RaisePropertyChanged("AuthorizedPersonId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.Guid AuthorizedPersonVersionId {
            get {
                return this.authorizedPersonVersionIdField;
            }
            set {
                this.authorizedPersonVersionIdField = value;
                this.RaisePropertyChanged("AuthorizedPersonVersionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public IszrVerificationStatus IszrVerificationStatus {
            get {
                return this.iszrVerificationStatusField;
            }
            set {
                this.iszrVerificationStatusField = value;
                this.RaisePropertyChanged("IszrVerificationStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=11)]
        public AuthPersonAddress[] Addresses {
            get {
                return this.addressesField;
            }
            set {
                this.addressesField = value;
                this.RaisePropertyChanged("Addresses");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aquasoft.eu/iska")]
    public enum AuthorizedPersonType {
        
        /// <remarks/>
        FO,
        
        /// <remarks/>
        FOP,
        
        /// <remarks/>
        PO,
        
        /// <remarks/>
        School,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aquasoft.eu/iska")]
    public enum IszrVerificationStatus {
        
        /// <remarks/>
        NotVerified,
        
        /// <remarks/>
        Correct,
        
        /// <remarks/>
        Incorrect,
        
        /// <remarks/>
        Unknown,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aquasoft.eu/iska")]
    public partial class RepresentativePersonQualification : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int qualificationIdField;
        
        private System.Guid representativePersonIdField;
        
        private System.DateTime validFromField;
        
        private System.DateTime validToField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int QualificationId {
            get {
                return this.qualificationIdField;
            }
            set {
                this.qualificationIdField = value;
                this.RaisePropertyChanged("QualificationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid RepresentativePersonId {
            get {
                return this.representativePersonIdField;
            }
            set {
                this.representativePersonIdField = value;
                this.RaisePropertyChanged("RepresentativePersonId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime ValidFrom {
            get {
                return this.validFromField;
            }
            set {
                this.validFromField = value;
                this.RaisePropertyChanged("ValidFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime ValidTo {
            get {
                return this.validToField;
            }
            set {
                this.validToField = value;
                this.RaisePropertyChanged("ValidTo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aquasoft.eu/iska")]
    public partial class AuthorizedPersonData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RepresentativePersonQualification[] representativePersonQualificationsField;
        
        private AuthPerson[] authorizedPersonsField;
        
        private AuthPersonQualification[] authorizedPersonQualificationsField;
        
        private RepresentativePerson[] represenatativePersonsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public RepresentativePersonQualification[] RepresentativePersonQualifications {
            get {
                return this.representativePersonQualificationsField;
            }
            set {
                this.representativePersonQualificationsField = value;
                this.RaisePropertyChanged("RepresentativePersonQualifications");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public AuthPerson[] AuthorizedPersons {
            get {
                return this.authorizedPersonsField;
            }
            set {
                this.authorizedPersonsField = value;
                this.RaisePropertyChanged("AuthorizedPersons");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public AuthPersonQualification[] AuthorizedPersonQualifications {
            get {
                return this.authorizedPersonQualificationsField;
            }
            set {
                this.authorizedPersonQualificationsField = value;
                this.RaisePropertyChanged("AuthorizedPersonQualifications");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public RepresentativePerson[] RepresenatativePersons {
            get {
                return this.represenatativePersonsField;
            }
            set {
                this.represenatativePersonsField = value;
                this.RaisePropertyChanged("RepresenatativePersons");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAuthorizations", WrapperNamespace="http://www.aquasoft.eu/iska", IsWrapped=true)]
    public partial class GetAuthorizationsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.aquasoft.eu/iska")]
        public Blog.GetAuthorizations.Access Access;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.aquasoft.eu/iska", Order=0)]
        public System.DateTime fromDate;
        
        public GetAuthorizationsRequest() {
        }
        
        public GetAuthorizationsRequest(Blog.GetAuthorizations.Access Access, System.DateTime fromDate) {
            this.Access = Access;
            this.fromDate = fromDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAuthorizationsResponse", WrapperNamespace="http://www.aquasoft.eu/iska", IsWrapped=true)]
    public partial class GetAuthorizationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.aquasoft.eu/iska", Order=0)]
        public Blog.GetAuthorizations.AuthorizedPersonData GetAuthorizationsResult;
        
        public GetAuthorizationsResponse() {
        }
        
        public GetAuthorizationsResponse(Blog.GetAuthorizations.AuthorizedPersonData GetAuthorizationsResult) {
            this.GetAuthorizationsResult = GetAuthorizationsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthorizationServiceSoapChannel : Blog.GetAuthorizations.AuthorizationServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthorizationServiceSoapClient : System.ServiceModel.ClientBase<Blog.GetAuthorizations.AuthorizationServiceSoap>, Blog.GetAuthorizations.AuthorizationServiceSoap {
        
        public AuthorizationServiceSoapClient() {
        }
        
        public AuthorizationServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthorizationServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthorizationServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthorizationServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blog.GetAuthorizations.GetAuthorizationsResponse Blog.GetAuthorizations.AuthorizationServiceSoap.GetAuthorizations(Blog.GetAuthorizations.GetAuthorizationsRequest request) {
            return base.Channel.GetAuthorizations(request);
        }
        
        public Blog.GetAuthorizations.AuthorizedPersonData GetAuthorizations(Blog.GetAuthorizations.Access Access, System.DateTime fromDate) {
            Blog.GetAuthorizations.GetAuthorizationsRequest inValue = new Blog.GetAuthorizations.GetAuthorizationsRequest();
            inValue.Access = Access;
            inValue.fromDate = fromDate;
            Blog.GetAuthorizations.GetAuthorizationsResponse retVal = ((Blog.GetAuthorizations.AuthorizationServiceSoap)(this)).GetAuthorizations(inValue);
            return retVal.GetAuthorizationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Blog.GetAuthorizations.GetAuthorizationsResponse> Blog.GetAuthorizations.AuthorizationServiceSoap.GetAuthorizationsAsync(Blog.GetAuthorizations.GetAuthorizationsRequest request) {
            return base.Channel.GetAuthorizationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Blog.GetAuthorizations.GetAuthorizationsResponse> GetAuthorizationsAsync(Blog.GetAuthorizations.Access Access, System.DateTime fromDate) {
            Blog.GetAuthorizations.GetAuthorizationsRequest inValue = new Blog.GetAuthorizations.GetAuthorizationsRequest();
            inValue.Access = Access;
            inValue.fromDate = fromDate;
            return ((Blog.GetAuthorizations.AuthorizationServiceSoap)(this)).GetAuthorizationsAsync(inValue);
        }
    }
}
